### ISSUE TITLE
Associate cdx.json extension with the media type 

### ISSUE THREAD

**Issue by samj1912** [CycloneDX/specification#100]
This is a completely optional request, but I was wondering if the CycloneDX team would be comfortable associating the extension `.cdx.json` to uniquely identify cyclonedx sbom json files? This would help with auto detection of cyclonedx bom files and provide some consistency around the file extension for users who want to be explicit about it.

Currently the cyclonedx json media type is associated with json file extension.

I am not sure if IANA allows you to update/add new extensions to an existing media type but I thought it was worth bringing this up in an issue for further discussion. For context SPDX uses spdx.json extension https://github.com/spdx/spdx-spec/issues/577#issuecomment-960295523 Here's the related syft issue where I describe the reasons behind a uniquely identifiable extension - https://github.com/anchore/syft/issues/612#issuecomment-962264996

**Comment by stevespringett** [comment]
I believe SPDX file naming requirements are part of the standard itself which is why the RFC needed to include spdx in the file extension. IMO, this is a legacy trait and was not adopted by CycloneDX. The primary purpose for the media types for CycloneDX adopters are for HTTP Accept headers where a client can request a specific type of SBOM and get that type back. Often times, these are not files. Its just machine-to-machine data transport. The CycloneDX BOM Repository Server and OWASP Dependency-Track both honor this behavior.

By convention, CycloneDX names their boms as `bom.json` and `bom.xml`. All official CycloneDX implementations and many community ones also follow this convention. It's similar to the convention used by Maven (pom.xml) and npm (package.json). So the auto detection algorithm should likely take this convention into consideration. 

Changing an IANA type would break compatibility for all CycloneDX adopters, so it's unlikely to happen.

Seeking input from @coderpatros and @DarthHater

**Comment by coderpatros** [comment]
> Changing an IANA type would break compatibility for all CycloneDX adopters, so it's unlikely to happen.

It could be an optional convention which shouldn't break compatibility.

But I'm of two minds about this. It helps for some use cases. But, IMHO, isn't a sufficient solution.

There's a bunch of projects now trying to support SBOMs of different formats side by side. But an extension like `.spdx.json` or `.cdx.json` only goes part of the way.

I know the SPDX folks are working on v3. So what happens for consumers when they release v3 with breaking changes? And how do publishers handle the transition period where they might want to publish v2 and v3 SBOMs side by side?

I'm in favour of it as an optional "official" convention. But I don't think it needs to be added to the media type registration. Which also supports specifying the spec version for the above reason.

**Comment by samj1912** [comment]
@coderpatros I am happy with this compromise if it's okay with you -

> I'm in favour of it as an optional "official" convention. But I don't think it needs to be added to the media type registration. Which also supports specifying the spec version for the above reason.

**Comment by samj1912** [comment]
Hi team - any thoughts on https://github.com/CycloneDX/specification/issues/100 ? As CI processes are creating multiple SBOMs per release, it is not viable to have a single file named `sbom.json`  having a common extension, even if it is just a documented convention would help a lot with auto detection of cdx sboms in various tools. `.cdx.json`  is already used in buildpacks and I was also thinking of proposing this extension to discover known sboms via syft (so that if an artifact already has pre-provided sboms. tools like syft can easily find and output them)) and to also trigger the auto-mime detection for cosign attach sbom feature.

**Comment by stevespringett** [comment]
> it is not viable to have a single file named bom.json

This should not occur as `spdx` is required to be part of the filename per spec.

Note that we will have to document two conventions.

1) bom.xml / bom.json as the default because that's what most people use today
2) bom.cdx.xml / bom.cdx.json as a fallback

Reason being is that bom.xml and bom.json are already being published to internal and public repos today.

**Comment by samj1912** [comment]
@stevespringett by multiple SBOMs per release, I meant that there are CI processes creating multiple cyclonedx SBOMs per release (for different components/containers/clis for eg.)

I was not too worried about interoperability with SPDX bom documents when this issue was created.

It was more along the lines of - lets say my CI process is creating CycloneDX SBOMs for - 

- myapp1 
- myapp2

and so on, I would like to create files like `myapp1.cdx.json` and `myapp2.cdx.json`.

**Comment by stevespringett** [comment]
Got it, understood. Thanks for clariifying.

**Comment by samj1912** [comment]
So given the above, does the following sound okay (made a small modification to the second point)? 

> Note that we will have to document two conventions.
> 
> - bom.xml / bom.json as the default because that's what most people use today
> - *.cdx.xml / *.cdx.json as a fallback

If so I am happy to submit a PR.

**Comment by stevespringett** [comment]
@coderpatros, @DarthHater: What are your thoughts? Should we document this in the READMD as well as the website?

**Comment by coderpatros** [comment]
Yeah, I think so. Probably good to add it to the spec overview below the registered media types https://github.com/CycloneDX/cyclonedx.org/blob/master/specification/overview/index.md

Having it there is also good for context. As in, where media types are available they should be used to infer the format. But the file extensions are a fallback option when you can't use the media types.
