### ISSUE TITLE
[BUG] `bom.properties` missing from JSON schema in version 1.4

### ISSUE THREAD

**Issue by madpah** [CycloneDX/specification#130]
When reviewing and comparing:
- https://cyclonedx.org/docs/1.4/xml/#element_bom
- https://cyclonedx.org/docs/1.4/json

...the JSON schema is missing `bom.properties` compared to the XML version.

FYI @stevespringett

**Comment by DarthHater** [comment]
@mr-zepol and I checked, it looks like we don't need to fix this with `cyclonedx-core-java`, I think we were "smart" and added it way back when, but it looks like maybe it didn't get added everywhere?

**Comment by jkowalleck** [comment]
@DarthHater I hope you were also smart when it came to output generation. Since CDX1.4 JSON schema is strict, it would not allow a `bom.properties` element at all. 
If you rendered such an element anway, then the resulting document would be considdered invalid as a whole, due to schema definitions. Tools that validate for the schema to check if a document suited the needs would claim that such a document would be unusable.

**Comment by stevespringett** [comment]
Scheduled for inclusion in v1.5
