### ISSUE TITLE
Link vulnerabilities to a SBOM component

### ISSUE THREAD

**Issue by javixeneize** [CycloneDX/specification#140]
Hi

The known vulnerability is based in CPE identifiers. Would it be possible to make it accept the same format as in the component section for libraries? Or maybe inside components, there can be section for vulnerabilities related to that component?

It is,  for example:

` {
	"components": [
	    {
	    	"type": "library",
	    	"group": "my.group",
	    	"name": "my.dep",
	    	"version": "0.1.0"
	    },
	 "vulnerabilities": [
	 	{
	 	"id": "CVE-2022-0001",
	 	"ratings": [
	 		{
		 		"score": 9.8,
		 		"severity": "critical"
	 		}
	 	],
	 	"description": "TEST"
	 	}
	]
   ]
}`

Thanks

**Comment by stevespringett** [comment]
> The known vulnerability is based in CPE identifiers.

is this a question or assumption? Not all known vulnerabilities are based on CPE. Its entirely possible to identify a CVE using PURL. You just cannot use the NVD to do it. But Snyk, Sonatype, VulnDB, etc, all support this without relying on CPE.

There are no plans to support vulnerabilities inside of a component element. We supported this with the legacy vulnerability extension, and quickly realized the many shortcomings of that approach. 

You'll want to include support for affects -> ref so that the vulnerability can refer to one or more components. See https://cyclonedx.org/docs/1.4/json/#vulnerabilities_items_affects_items_ref

**Comment by javixeneize** [comment]
Hi Steve :)

Thanks, i think the affects item ref would work

Thanks
