### ISSUE TITLE
Addition of timestamps to analysis in VEX

### ISSUE THREAD

**Issue by msymons** [CycloneDX/specification#142]
I would like to see the specification support analysis timestamps in VEX

There are timestamps for each vulnerability:
* created
* published
* updated

Without a timestamp for analysis, it is not possible to determine if (for example) analysis was performed BEFORE the vulnerability was updated.  This can really matter in cases where understanding of a vulnerability can change hugely after it was first published.

**Comment by stevespringett** [comment]
@msymons do you see this as a single property called `timestamp` which would act as the last time the analysis was changed? Or do you envision the analysis having a time stamp for when the first time an analysis was made along with a last updated timestamp?

I'm leaning towards the first scenario where a single timestamp property is added. Otherwise, I think we can get into situations where users would ask for a history of analysis decisions in a single BOM. This use case can already be achieved by using the `version` property of the bom.

**Comment by msymons** [comment]
I think that the former is fine, a `timestamp` representing last analysis.

I agree that versioned BOMs allow the analysis decision history to be explored in more depth, if needed.  After all, not everyone will be concerned with the history just like some will not even be concerned with the `timestamp`...  but much capability can flow from making use of both.

**Comment by stevespringett** [comment]
Scheduled for inclusion in v1.5
