### ISSUE TITLE
License documentation broke in JSON schema

### ISSUE THREAD

**Issue by stevespringett** [CycloneDX/specification#257]
JSON documentation for license broke due to #205. Fixing a minor defect in the schema has caused a major defect in the JSON documentation that users consume. May need to revert #205 until such time as we can figure out a way to solve both.

**Comment by stevespringett** [comment]
v1.4 schema docs:
<img width="1592" alt="Screenshot 2023-06-22 at 5 42 11 PM" src="https://github.com/CycloneDX/specification/assets/3878933/90e70b29-6d27-4182-8594-e970c1a6aadf">

Current v1.5 schema docs:
<img width="1589" alt="Screenshot 2023-06-22 at 5 41 47 PM" src="https://github.com/CycloneDX/specification/assets/3878933/e9c08260-b6fc-4f62-b099-8d6beced95ce">

**Comment by stevespringett** [comment]
@jkowalleck Can you take a look please?

**Comment by jkowalleck** [comment]
was looking at the artifacts of https://github.com/CycloneDX/specification/actions/runs/5351307657
:mag: what I found: the documentation is unable to render the "oneOf" at all, for SOME (not all). 
other ocurrences of non-working oneOf's:
- 
- `formulation.items.workflows.items.resourceReferences.items`
- `formulation.items.workflows.items.inputs.items`
in contrsst there are "oneOf"s that are working as expected:
- `metadata.tools`
- `components.items.modelCard.modelParameters.datasets.items`

i found out, that the common factor for all non-working other ocurrences were, that they used the `required` field in a one-of, but the actually required properties were defined in the parent of the oneOF.
i actually had tests for this ocurrences, that were just too noisy and non-fixable due to the way the schema was defined.
see https://github.com/CycloneDX/specification/blob/v1.5-dev/tools/src/test/js/json-schema-lint-tests.js#L39-L48


i will try to find and fix those issues.

**Comment by jkowalleck** [comment]
@stevespringett fix via #258
