### ISSUE TITLE
Can VEX report have duplicate ids

### ISSUE THREAD

**Issue by ilans** [CycloneDX/specification#267]
According to the spec, `vulnerabilities.id` is: 
> The identifier that uniquely identifies the vulnerability.

Does this mean that `vulnerabilities.id` should be unique per VEX report?
If it doesn't need to be, in which use case would it make sense to list the same vulnerability multiple times?

**Comment by jkowalleck** [comment]
The `vulnerabilities.id` is to be globally unique – not only in the universe of one CycloneDX document, but in general.
It could be a [CVE identifier](https://en.wikipedia.org/wiki/Common_Vulnerabilities_and_Exposures) or a similar value.
see use cases: https://cyclonedx.org/use-cases/#vulnerability-exploitability
see examples: https://github.com/CycloneDX/bom-examples/tree/master/VEX

**Comment by dn-scribe** [comment]
I think the question is: can the ```vulnerabilities``` field include more that one element with the same id. 

The use cases for this are to enable to express that a specific CVE is relevant to more than one component, and to express the different analysis (and scores) relevant to that component.

For example, suppose both components A,B are binaries that include component C. The SBOM may include A and B, but not C (It may not have been visible to the SCA), but NVD data points that both A and B are vulnerable (due to their inclusion of C) to the same CVE.

The current CycloneDX structures enables (as far as I understand) to connect each vulnerability object to one ```bom-ref```, so the way to point to A and B is by creating two vulnerabilitie objects. but the above answer suggests it is not legit.

I think it should be supported. 

Hope I was clear.

**Comment by mrutkows** [comment]
> I think the question is: can the `vulnerabilities` field include more that one element with the same id.

That is how I read it as well... the current schema has for vulnerabilities:
```
        "id": {
          "type": "string",
          "title": "ID",
          "description": "The identifier that uniquely identifies the vulnerability.",
          "examples": [
            "CVE-2021-39182",
            "GHSA-35m5-8cvj-8783",
            "SNYK-PYTHON-ENROCRYPT-1912876"
          ]
        },
```

and the "vulnerabilites" array has:
``` "uniqueItems": true," ```

However, this is interpreted in diff. ways in code (and not based strictly in the ID). Often, the entire object has to me 100% duplicated (i.e., a deep clone)
