### ISSUE TITLE
Show comments of JSON Schema in Documentation

### ISSUE THREAD

**Issue by andreas-hilti** [CycloneDX/specification#336]
The comments that are part of the JSON schema are not shown in the documentation. Can they be added?

Example:
refType has a comment
> "$comment": "value SHOULD not start with the BOM-Link intro 'urn:cdx:'"

https://github.com/CycloneDX/specification/blob/299209abd9531d808e0cc4235e77a7c4b1b53d96/schema/bom-1.5.schema.json#L123-L128

However, this does not show up in the documentation:
https://cyclonedx.org/docs/1.5/json/#metadata_component_bom-ref
![grafik](https://github.com/CycloneDX/specification/assets/69210561/23a8323a-0bc8-4c87-afb3-ebb6f067ba46)

**Comment by andreas-hilti** [comment]
This is similar in spirit to https://github.com/CycloneDX/specification/issues/273.

**Comment by jkowalleck** [comment]
https://github.com/coveooss/json-schema-for-humans/issues/198

**Comment by jkowalleck** [comment]
What you are referring to is a comment by me, the author. This is nothing relevant for documentation, so I thought at the time I wrote it.

The fact that the  "value SHOULD not start with the BOM-Link intro 'urn:cdx:'" was stated, because it was a note for readers of the schema, in case they needed it for deeper understanding of the background of the change i made via https://github.com/CycloneDX/specification/commit/626dbbc824f7eb1ed011bedfa87a3dd8192b8698

**Comment by andreas-hilti** [comment]
Thanks, @jkowalleck. In my opinion, there are two aspects:
- (I learned that) $comment should contain only information for schema maintainers, not for the users, compare https://json-schema.org/understanding-json-schema/reference/comments (in agreement with your statement).
  Nevertheless, I would see some value if $comments were available, as it is also about maintaining the json schema. But let's see what comes out of https://github.com/coveooss/json-schema-for-humans/issues/198
- A comment like "value SHOULD not start with the BOM-Link intro 'urn:cdx:'" is directed to the users, thus it would probably be better suited in the description.

I can open a PR.

**Comment by jkowalleck** [comment]
> I can open a PR. 
please do :+1:

**Comment by jkowalleck** [comment]
all work done. enhancement was merged to 1.6
