### ISSUE TITLE
RFC Inclusion of license information in SBOM metadata

### ISSUE THREAD

**Issue by coderpatros** [CycloneDX/specification#40]
I think we should include in the SBOM metadata information on whether the SBOM is re-distributable, etc.

I think this goal can be achieved by including the existing licenseType as an element in the SBOM metadata.

**Comment by stevespringett** [comment]
My initial thought on this is that 1) its useful and needed, and 2) distribution terms may vary based on contract. 

It would be possible (and highly probable) that a single SBOM may be re-distributed under certain terms to business partners for example, one-way distributable to customers or any org under NDA, and not distributable to non customers. 

The suppliers relationship to others will also vary over time.

It may make sense to bring in others to this conversation so we can capture the nuance and try to determine if we can easily do this in the core, or if we'll need an extension to support a wide variety of scenarios.

**Comment by coderpatros** [comment]
I think it would be good to bring in some others on this too.

But my initial thoughts are that we should keep it simple. The current license element is fairly flexible as you can include license text to cover more complicated/contractual scenarios.

And I said the licenseType, but I really meant the way it is included on components.

```
   <bom:licenses   > [0..1] 
      Start Choice [1]
         <bom:license> bom:licenseType </bom:license> [0..*]
         <bom:expression> xs:normalizedString </bom:expression> [0..1] 
      End Choice
   </bom:licenses>
```

**Comment by stevespringett** [comment]
Got it. So bom-level license element. That may actually work.

My initial thought is that for SBOMs for open source projects, we should likely recommend use of [CC by-ND](https://creativecommons.org/licenses/by-nd/4.0/) (although we should likely discuss with the SPDX folks so that we can align). Then for proprietary, the license name with optional attached text (as you've stated) will likely cover complicated contractual use cases.

That approach aligns with the projects objectives.

I think this is certainly one area where SPDX, CycloneDX, and perhaps the NTIA framing group can provide some guidance and alignment.

**Comment by coderpatros** [comment]
Does the ND part of CC by-ND cause issues? I'm thinking use cases like using upstream supplied component level SBOMs when creating an assembled software SBOM?

And it might bother some security product vendors who might want to augment an SBOM with vulnerability/exploitability information. Or potentially other use cases we aren't aware of yet. (IMHO that sort of stuff doesn't belong in an SBOM, but I wouldn't want to block people from doing it)

But I agree about aligning with the SPDX folks and seeking some guidance from NTIA framing group on what license should be recommended.

**Comment by johnmod3** [comment]
This just seems like it would get overly complicated and meta after awhile
- I’m not sure allowing a copyright on the SBOM would be good.

For example: a vendor might not be able to rehost a SBOM if marked badly

just 2 cents

-------------------------------------------
John Scott
 240.401.6574
< jms3rd@gmail.com >
ionchannel.io

On October 26, 2020 at 3:14:08 AM, Patrick Dwyer (notifications@github.com)
wrote:

Does the ND part of CC by-ND cause issues? I'm thinking use cases like
using upstream supplied component level SBOMs when creating an assembled
software SBOM?

And it might bother some security product vendors who might want to augment
an SBOM with vulnerability/exploitability information. Or potentially other
use cases we aren't aware of yet. (IMHO that sort of stuff doesn't belong
in an SBOM, but I wouldn't want to block people from doing it)

But I agree about aligning with the SPDX folks and seeking some guidance
from NTIA framing group on what license should be recommended.

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/CycloneDX/specification/issues/40#issuecomment-716355288>,
or unsubscribe

**Comment by coderpatros** [comment]
I'm no lawyer, but I think an SBOM would be automatically protected by copyright to some extent. And in the absence of a permissive license a vendor couldn't confidently rehost an SBOM anyway. 

Does anyone know if this has come up, and been answered, in any of the NTIA discussions?

**Comment by johnmod3** [comment]
I don’t think it has, but you do make a good point 

 Via phone
.... John Scott 
Ion Channel 
240.401.6574
Ionchannel.io

**Comment by coderpatros** [comment]
I might be misinterpreting this, but it looks like the Linux Foundation is trying to enforce CC0 1.0 for all SPDX files. From the current SPDX spec...

```
2.2.1 Purpose: Compliance with the SPDX specification includes populating the SPDX fields therein with data related to such fields ("SPDX-Metadata"). The SPDX specification contains numerous fields where an SPDX document creator may provide relevant explanatory text in SPDX-Metadata. Without opining on the lawfulness of "database rights" (in jurisdictions where applicable), such explanatory text is copyrightable subject matter in most Berne Convention countries. By using the SPDX specification, or any portion hereof, you hereby agree that any copyright rights (as determined by your jurisdiction) in any SPDX-Metadata, including without limitation explanatory text, shall be subject to the terms of the Creative Commons CC0 1.0 Universal license. For SPDX-Metadata not containing any copyright rights, you hereby agree and acknowledge that the SPDX-Metadata is provided to you "as-is" and without any representations or warranties of any kind concerning the SPDX-Metadata, express, implied, statutory or otherwise, including without limitation warranties of title, merchantability, fitness for a particular purpose, non-infringement, or the absence of latent or other defects, accuracy, or the presence or absence of errors, whether or not discoverable, all to the greatest extent permissible under applicable law.

2.2.2 Intent: This is to alleviate any concern that content (the data or database) in an SPDX file is subject to any form of intellectual property right that could restrict the re-use of the information or the creation of another SPDX file for the same project(s). This approach avoids intellectual property and related restrictions over the SPDX file, however individuals can still contract with each other to restrict release of specific collections of SPDX files (which map to software bill of materials) and the identification of the supplier of SPDX files.
```

I think I understand what they are trying to address. But I'm surprised this hasn't made some MDMs nervous as part of the NTIA work.

Anyway, I'm not completely against it as a default license. But I don't support making it a requirement when using the CycloneDX spec.

**Comment by coderpatros** [comment]
Implementation being tracked in #51
